### ISSUE TITLE
Auto-Generated Daily Tasks

### ISSUE THREAD

**Issue by E-3P0** [Azurekuz/RPG-Task-Manager#13]
User should be able to enable tasks from the default pool of daily tasks to automatically generate each day.

**Comment by Azurekuz** [comment]
**Additional Info:** Tasks that are denoted as "Daily Tasks" in any pool, will be added to the Daily Task list upon being selected. Additionally, Daily Tasks will be automatically assigned a time limit according to how many hours are left in the day.

**Comment by Azurekuz** [comment]
Currently daily tasks can be selected and get auto-added to the Daily Tasks list instead of current tasks. There is also a function to auto-populate the Current Task list with Dailies, which will get called at every new day. I'm presently stuck on assigning time limits according to how many hours are left in the day. I will try again tomorrow.

Time Taken (so far): 1.75 hours

**Comment by Azurekuz** [comment]
Spent time fiddling around with Date and LocalDateTime, trying to figure out how to calculate/recalculate the time limit for Daily tasks. Their time limit is based off of how many hours are left in the current day. Was a hassle wrangling with Java's multiple formats/ways of handling this.

+1.25 hours

Time taken (so far): 3 hours

**Comment by Azurekuz** [comment]
+0.5 hours
Figured out and solved an issue where Dailies weren't being given a start time when populating the current task list.

Time Taken: 3.5 hours
