### ISSUE TITLE
TaskUI error catching & testing

### ISSUE THREAD

**Issue by E-3P0** [Azurekuz/RPG-Task-Manager#95]

**Comment by Azurekuz** [comment]
**Demo:** Going through the process of entering commands and selecting tasks, typing incorrect or imprecise options (i.e. Typing in 'SELECT' rather than 'select'), and demonstrating that an error is printed out and the program remains functional.

Error Catching now works for Selecting, Editing, Stopping, and Completing tasks.

Time Taken (so far): 1 hour

**Comment by tobydragon** [comment]
No how to demo...

**Comment by E-3P0** [comment]
Fixed merge conflicts & stuff with main tasks branch (see added time on card #1)

Done for now.

**Comment by Azurekuz** [comment]
Added more error catching for user inputs.
Time Taken (so far): 1.3 hours
